baseURL = "https://portfolio.harukaashiuchi.me/"
languageCode = "ja-jp"
title = "Haruka Ashiuchi Portfolio"
defaultContentLanguage = "ja"
hasSJKLanguage = true
theme = "etch"
publishDir = "docs"

[outputs]
    page = ["HTML","AMP"]
 
 [Params]
    profile_image = "images/profile.jpg"
    eyecatch = "images/eyecatch.jpg"
    author = "Haruka Ashiuchi"

[taxonomies]
    tag = "tags"

[permalinks]
    post = "/:section/:year/:month:/:filename"

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    extensionsmask = ["autolink"]

[menu]
    [[menu.global_header]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.global_header]]
        name = "Project"
        url = "/projects"
        weight = 2
    [[menu.global_header]]
        name = "Blog"
        url = "/post"
        weight = 3